# Generated by Django 3.0 on 2022-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220428_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zoom',
            field=models.CharField(max_length=255, verbose_name='zoom'),
        ),
    ]
