# Generated by Django 3.0 on 2022-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220524_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delete_status',
            field=models.BooleanField(default=1),
        ),
    ]
