"""
Django settings for navankur project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ywe%&pns!s&u&0&&hx83bb+*xq^8gg^7^f^x3()5ckrmpery(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'app',
    'users',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ROOT_URLCONF = 'navankur.urls'
# AUTH_USER_MODEL = 'accounts.User'

EMAIL_USE_TLS = True

##for gmail email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
#
# EMAIL_HOST_USER = 'mohdkaif@radiantinfonet.com'
#

# EMAIL_HOST_USER = 'kkaifkhan1040@gmail.com'
# EMAIL_HOST_USER = 'radiantinfonet901@gmail.com'
# EMAIL_HOST_USER = 'kaifkhan11110000@gmail.com'

# EMAIL_HOST_PASSWORD = 'Radiant@901'
# EMAIL_HOST_PASSWORD = 'coral@123'
# EMAIL_HOST_PASSWORD = 'wcgrphbnxbjhktzk'
# EMAIL_HOST_PASSWORD = 'dzfwbeepllefgdrw'
# EMAIL_PORT = 587

## for outlook mail.
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#
# EMAIL_HOST = 'smtp-mail.outlook.com'
#
# # EMAIL_HOST_USER = 'support@radiantinfonet.com'
EMAIL_HOST_USER = 'support@navankur.org'
# # EMAIL_HOST_USER = 'kaifkhan11110000@gmail.com'
# #
# # EMAIL_HOST_PASSWORD = 'coral@123'
# EMAIL_HOST_PASSWORD = 'Radiant@901'
#
# EMAIL_PORT = 587

# server_name='smtp.office365.com'
# port= 587
# encryption_method= 'SSL'
# SMTP_authentication= 'ticked'
# Authentication= 'Radiant@901'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'admin@navankur.org'
EMAIL_HOST_PASSWORD = 'Radiant@901'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'navankur.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# REST_FRAMEWORK = {
# 'DEFAULT_AUTHENTICATION_CLASSES': [
#     # 'rest_framework.authentication.SessionAuthentication',
#     'rest_framework.authentication.BasicAuthentication',
# ]
# }
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'navankurfarmer',
        'NAME': 'newnavankur',
        # 'NAME': 'navankurnew',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',

    },
    'OPTIONS': {'init_command': 'SET storage_engine=MyISAM', },
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')

]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/user/login'