# Generated by Django 3.2 on 2022-06-21 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_cbbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fpo_name', models.CharField(max_length=50)),
                ('registered_address', models.CharField(max_length=300)),
                ('terrain_category', models.CharField(max_length=10)),
                ('cbbo_name', models.CharField(max_length=20)),
                ('ia_name', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('fpo_contact_person_name', models.CharField(max_length=128)),
                ('contact_person_mobile_no', models.CharField(max_length=10)),
                ('fpo_email_id', models.CharField(max_length=255)),
                ('office_address_proof', models.CharField(max_length=500)),
                ('rent_agreement', models.CharField(max_length=500)),
                ('photo_graph_of_the_fpo', models.CharField(max_length=500)),
                ('coi_number', models.CharField(max_length=20)),
                ('coi_doc', models.CharField(max_length=500)),
                ('pan_card_of_fpo', models.CharField(max_length=10)),
                ('pan_card_doc_of_fpo', models.CharField(max_length=500)),
                ('tan_of_fpo', models.CharField(max_length=10)),
                ('tan_doc_of_fpo', models.CharField(max_length=500)),
                ('moa', models.CharField(max_length=500)),
                ('aoa', models.CharField(max_length=500)),
                ('gst_certificate', models.CharField(max_length=10)),
                ('gst_certificate_doc', models.CharField(max_length=500)),
                ('udhyog_aadhar_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=15)),
                ('bank_branch', models.CharField(max_length=128)),
                ('full_address', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'fpo',
            },
        ),
    ]
