# Generated by Django 3.2 on 2022-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscriberdetails_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='udhyog_aadhar_doc',
            field=models.ImageField(default=1, upload_to='fpo/udhyog_aadhar_doc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fpo',
            name='aoa',
            field=models.ImageField(upload_to='fpo/aoa'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='coi_doc',
            field=models.ImageField(upload_to='fpo/coi_doc'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='gst_certificate_doc',
            field=models.ImageField(upload_to='fpo/gst_certificate_doc'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='moa',
            field=models.ImageField(upload_to='fpo/moa'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='office_address_proof',
            field=models.ImageField(upload_to='fpo/address_proof'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='pan_card_doc_of_fpo',
            field=models.ImageField(upload_to='fpo/pan_card_doc'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='photo_graph_of_the_fpo',
            field=models.ImageField(upload_to='fpo/fpo_photo_graph'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='rent_agreement',
            field=models.ImageField(upload_to='fpo/rent_agreement'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='tan_doc_of_fpo',
            field=models.ImageField(upload_to='fpo/tan_doc'),
        ),
    ]
