# Generated by Django 3.2 on 2022-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220621_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberdetails',
            name='aadhar_card_doc',
            field=models.ImageField(default=1, upload_to='subscriberdetails/aadhar_card_doc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='aadhar_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='khasra_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='khasra_number_doc',
            field=models.ImageField(default=1, upload_to='subscriberdetails/khasra_number_doc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='land_holding',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='land_holding_doc',
            field=models.ImageField(default=1, upload_to='subscriberdetails/land_holding_doc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='pan_card_doc',
            field=models.ImageField(default=1, upload_to='subscriberdetails/pan_card_doc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='pan_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='photo',
            field=models.ImageField(upload_to='subscriberdetails/photo'),
        ),
    ]
