# Generated by Django 3.2 on 2022-06-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220621_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpoBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=15)),
                ('bank_branch', models.CharField(max_length=128)),
                ('full_address', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='subscriberdetails',
            name='fpo_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fpo'),
            preserve_default=False,
        ),
    ]
