# Generated by Django 3.2 on 2022-06-21 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220621_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpoAuthorisedPersonInBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='FpoBankDetails',
        ),
        migrations.AddField(
            model_name='fpo',
            name='Passbook',
            field=models.ImageField(default=1, upload_to='fpo/Passbook/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='account_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_branch',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_statement_doc',
            field=models.ImageField(default=1, upload_to='fpo/bank_statement_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_aadhar_card_doc',
            field=models.ImageField(default=1, upload_to='fpo_accountant/fpo_accountant_aadhar_card_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_aadhar_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_appointment_letter',
            field=models.ImageField(default=1, upload_to='fpo_accountant/fpo_accountant_appointment_letter/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_contact_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_education_documents',
            field=models.ImageField(default=1, upload_to='fpo_accountant/fpo_accountant_education_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_email_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_first_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_last_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_middle_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_pan_card_doc',
            field=models.ImageField(default=1, upload_to='fpo_accountant/fpo_accountant_pan_card_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_pan_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_resume',
            field=models.ImageField(default=1, upload_to='fpo_accountant/fpo_accountant_resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_aadhar_card_doc',
            field=models.ImageField(default=1, upload_to='fpo_ceo/fpo_ceo_aadhar_card_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_aadhar_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_appointment_letter',
            field=models.ImageField(default=1, upload_to='fpo_ceo/appointment_letter/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_contact_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_education_documents',
            field=models.ImageField(default=1, upload_to='fpo_ceo/education_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_email_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_first_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_last_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_middle_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_pan_card_doc',
            field=models.ImageField(default=1, upload_to='fpo_ceo/fpo_pan_card_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_pan_card_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_resume',
            field=models.ImageField(default=1, upload_to='fpo_ceo/resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='full_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fpo',
            name='aoa',
            field=models.ImageField(upload_to='fpo/aoa/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='coi_doc',
            field=models.ImageField(upload_to='fpo/coi_documents/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='gst_certificate_doc',
            field=models.ImageField(upload_to='fpo/gst_certificate_documents/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='moa',
            field=models.ImageField(upload_to='fpo/moa/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='office_address_proof',
            field=models.ImageField(upload_to='fpo/address_proof/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='pan_card_doc_of_fpo',
            field=models.ImageField(upload_to='fpo/pan_card_documents/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='photo_graph_of_the_fpo',
            field=models.ImageField(upload_to='fpo/fpo_photo_graph/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='rent_agreement',
            field=models.ImageField(upload_to='fpo/rent_agreement/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='tan_doc_of_fpo',
            field=models.ImageField(upload_to='fpo/tan_documents/'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='udhyog_aadhar_doc',
            field=models.ImageField(upload_to='fpo/udhyog_aadhar_documents/'),
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='aadhar_card_doc',
            field=models.ImageField(upload_to='subscriberdetails/aadhar_card_documents/'),
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='khasra_number_doc',
            field=models.ImageField(upload_to='subscriberdetails/khasra_number_documents/'),
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='land_holding_doc',
            field=models.ImageField(upload_to='subscriberdetails/land_holding_documents/'),
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='pan_card_doc',
            field=models.ImageField(upload_to='subscriberdetails/pan_card_documents/'),
        ),
        migrations.AlterField(
            model_name='subscriberdetails',
            name='photo',
            field=models.ImageField(upload_to='subscriberdetails/photo/'),
        ),
        migrations.AddField(
            model_name='fpoauthorisedpersoninbank',
            name='fpo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fpo'),
        ),
    ]
