# Generated by Django 3.2 on 2022-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='fpo_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fpo'),
            preserve_default=False,
        ),
    ]
