# Generated by Django 3.2 on 2022-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_farmer_fpo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbbo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
