# Generated by Django 3.2 on 2022-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cbbo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='cin',
            field=models.CharField(default=1, max_length=21),
            preserve_default=False,
        ),
    ]
