# Generated by Django 3.2 on 2022-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_fpo_cin'),
    ]

    operations = [
        migrations.CreateModel(
            name='terrain_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, unique=True)),
                ('delete_status', models.BooleanField(default=True)),
            ],
        ),
    ]
