# Generated by Django 3.2 on 2022-07-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220628_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpo',
            old_name='registered_address',
            new_name='registered_address_line1',
        ),
        migrations.AddField(
            model_name='fpo',
            name='registered_address_line2',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
