# Generated by Django 3.2 on 2022-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220704_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='land_mark',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
