# Generated by Django 3.2 on 2022-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_fpo_land_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberdetails',
            name='type',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
