# Generated by Django 3.2 on 2022-07-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_subscriberdetails_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpoBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=16)),
                ('branch', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=500)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_statement_doc', models.ImageField(upload_to='fpo/bank/bank_statement/')),
                ('passbook_doc', models.ImageField(upload_to='fpo/bank/passbook_doc/')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fpo')),
            ],
        ),
    ]
