# Generated by Django 3.2 on 2022-07-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_fpobankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpo',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='ifsc_code',
        ),
    ]
