# Generated by Django 3.2 on 2022-07-07 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220707_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='crop_name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='crop_type',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='date_of_commencement',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='is_fpo_women_centric',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
