# Generated by Django 3.2 on 2022-07-07 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220707_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpoAaInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('firm_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompnayMeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metting_type', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('purpose', models.CharField(max_length=128)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fpo')),
            ],
        ),
    ]
