# Generated by Django 3.2 on 2022-07-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_fpoaainformation_fpocainformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpocainformation',
            name='fpo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fpo'),
            preserve_default=False,
        ),
    ]
