# Generated by Django 3.2 on 2022-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_fpocainformation_fpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberdetails',
            name='email_id',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
