# Generated by Django 3.2 on 2022-07-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_subscriberdetails_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpo',
            name='fpo_accountant_education_documents',
        ),
        migrations.CreateModel(
            name='FpoAccountantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
                ('education_documents', models.ImageField(upload_to='fpo_accountant/fpo_accountant_education_documents/')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fpo')),
            ],
        ),
    ]
