# Generated by Django 3.2 on 2022-07-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220713_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpoaccountanteducation',
            old_name='education',
            new_name='accountant_education',
        ),
        migrations.RenameField(
            model_name='fpoaccountanteducation',
            old_name='education_documents',
            new_name='accountant_education_documents',
        ),
        migrations.RenameField(
            model_name='fpoceoeducation',
            old_name='education',
            new_name='ceo_education',
        ),
        migrations.RenameField(
            model_name='fpoceoeducation',
            old_name='education_documents',
            new_name='ceo_education_documents',
        ),
    ]
