# Generated by Django 3.2 on 2022-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220713_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
