# Generated by Django 3.2 on 2022-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20220719_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberdetails',
            name='email_id',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
