# Generated by Django 3.2 on 2022-07-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_subscriberdetails_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_education_documents',
            field=models.ImageField(default=1, upload_to='fpo_ceo/education_documents/'),
            preserve_default=False,
        ),
    ]
