# Generated by Django 3.2 on 2022-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_fpo_fpo_ceo_education_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpo',
            name='fpo_ceo_education_documents',
        ),
        migrations.AlterField(
            model_name='fpocainformation',
            name='email_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
