# Generated by Django 3.2 on 2022-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20220721_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpobankdetails',
            name='bank_statement_doc',
            field=models.ImageField(default=1, upload_to='fpo/bank/bank_statement/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpobankdetails',
            name='passbook_doc',
            field=models.ImageField(default=1, upload_to='fpo/bank/passbook_doc/'),
            preserve_default=False,
        ),
    ]
