# Generated by Django 3.2 on 2022-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_issuedsharedcapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='compnaymeetingdetails',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
