# Generated by Django 3.2 on 2022-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_compnaymeetingdetails_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpoceoeducation',
            name='ceo_education_documents',
            field=models.ImageField(upload_to='fpo_ceo/fpo_ceo_education_documents/'),
        ),
    ]
