# Generated by Django 3.0 on 2022-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fpo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_title', models.CharField(max_length=128)),
                ('state_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
