# Generated by Django 3.0 on 2022-05-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='state_id',
            new_name='state',
        ),
    ]
