# Generated by Django 3.0 on 2022-05-19 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220517_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo',
            name='account_holder_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='additional_services_proposed_by_fpo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='authorise_share_capital',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='authorise_signatory_in_bank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='bank_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='branch_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bussiness_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='bussiness_transation_ammount_details',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='bussiness_transation_details',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='cin_no',
            field=models.CharField(default=1, max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='company_aoa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='company_moa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='company_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='date_of_incorporation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='dates_of_board_meeting',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='dmc_approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='email_created_by',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='email_id_of_ca',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fig_creation_remarks',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='first_general_board_meetings',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_email_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_accountant_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_email_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_ceo_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_formed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_office_post_office',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_office_village_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_registration_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_registration_remarks',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='fpo_udyog_aadhaar',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='full_address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='gst_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='is_woman_centric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='issued_shared_capital',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='mca_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='mobile_no_of_ca',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='mobile_no_registered_with_email',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='name_of_ca',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='name_of_mandi',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='no_of_board_meetings',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='no_of_bods',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='no_of_farmer_mobilized',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='no_of_share_member',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='obtained_commencement_end_of_bussiness_certificate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fpo',
            name='pan_card_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='pan_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='pin_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='primary_crop_approved_by_dmc_or_as_per_dpr',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='register_on_enam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='registration_act',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='secondary_crop_approved_by_dmc_or_as_per_dpr',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='special_allocation',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='status_accountant_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='status_board_meamber_identification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='status_ceo_appointment',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='status_of_baseline_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='status_of_ca_appointing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='tan_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpo',
            name='tan_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='total_equity_amount',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo',
            name='villages_covered_under_fpo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
    ]
