# Generated by Django 3.2 on 2022-06-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220621_1119'),
        ('app', '0005_auto_20220621_1123'),
        ('app', '0021_auto_20220621_1115'),
        ('app', '0021_auto_20220621_1116'),
        ('app', '0022_auto_20220621_1038'),
        ('app', '0022_cbbo'),
    ]

    operations = [
    ]
